import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>
        <div className=" flex flex-col ">
          <div className=" bg-pink-500 px-5 z-50 sticky top-0  ">
            <Header />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
